export type AirdropStatus = "active" | "upcoming" | "ended"

export interface Airdrop {
  id: string
  name: string
  symbol: string
  description: string
  status: AirdropStatus
  chain: string
  estimatedValue: string
  endDate: string
  requirements: string[]
  website: string
  featured: boolean
}

export interface Article {
  id: string
  title: string
  excerpt: string
  content: string
  author: string
  publishedAt: string
  readTime: string
  category: string
  slug: string
}

export const airdrops: Airdrop[] = [
  {
    id: "1",
    name: "LayerZero",
    symbol: "ZRO",
    description: "LayerZero is an omnichain interoperability protocol for lightweight cross-chain messaging.",
    status: "active",
    chain: "Omnichain",
    estimatedValue: "$100 - $5,000",
    endDate: "2026-05-09",
    requirements: ["Bridge assets using LayerZero", "Use Stargate Finance", "Interact with cross-chain dApps"],
    website: "https://layerzero.network",
    featured: true,
  },
  {
    id: "2",
    name: "zkSync",
    symbol: "ZK",
    description: "zkSync is a zk-rollup scaling solution for Ethereum with low fees and fast finality.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$50 - $3,000",
    endDate: "2026-05-09",
    requirements: ["Bridge ETH to zkSync", "Swap tokens on zkSync", "Use zkSync dApps"],
    website: "https://zksync.io",
    featured: true,
  },
  {
    id: "3",
    name: "Scroll",
    symbol: "SCR",
    description: "Scroll is a native zkEVM Layer 2 network built on Ethereum.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$100 - $2,500",
    endDate: "2026-05-09",
    requirements: ["Bridge assets to Scroll", "Use Scroll dApps", "Participate in the ecosystem"],
    website: "https://scroll.io",
    featured: true,
  },
  {
    id: "4",
    name: "Starknet",
    symbol: "STRK",
    description: "Starknet is a decentralized ZK-rollup focused on Ethereum scalability.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$80 - $2,800",
    endDate: "2026-05-09",
    requirements: ["Use Starknet applications", "Join the community", "Follow official updates"],
    website: "https://starknet.io",
    featured: true,
  },
  {
    id: "5",
    name: "Base",
    symbol: "BASE",
    description: "Base is a Coinbase-backed Ethereum Layer 2 focused on low fees and security.",
    status: "active",
    chain: "Base",
    estimatedValue: "$75 - $1,500",
    endDate: "2026-05-09",
    requirements: ["Bridge to Base", "Use Base apps", "Participate in promotions"],
    website: "https://base.org",
    featured: true,
  },
  {
    id: "6",
    name: "Linea",
    symbol: "LINEA",
    description: "Linea is a zkEVM network by ConsenSys for Ethereum scaling.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$70 - $1,200",
    endDate: "2026-05-09",
    requirements: ["Bridge assets to Linea", "Use Linea dApps", "Join the Linea community"],
    website: "https://linea.build",
    featured: false,
  },
  {
    id: "7",
    name: "Fuel",
    symbol: "FUEL",
    description: "Fuel is a modular execution layer blockchain built for high-performance transactions.",
    status: "active",
    chain: "Layer 2",
    estimatedValue: "$60 - $1,800",
    endDate: "2026-05-09",
    requirements: ["Use Fuel wallet", "Swap on Fuel", "Explore Fuel apps"],
    website: "https://fuel.network",
    featured: false,
  },
  {
    id: "8",
    name: "Manta Network",
    symbol: "MANTA",
    description: "Manta Network is a privacy-focused blockchain ecosystem on Polkadot.",
    status: "active",
    chain: "Polkadot",
    estimatedValue: "$120 - $2,000",
    endDate: "2026-05-09",
    requirements: ["Join Manta Network", "Use private transfers", "Follow the community"],
    website: "https://manta.network",
    featured: false,
  },
  {
    id: "9",
    name: "Blast",
    symbol: "BLAST",
    description: "Blast is an Ethereum Layer 2 delivering native yield and high throughput.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$90 - $2,200",
    endDate: "2026-05-09",
    requirements: ["Bridge to Blast", "Use Blast dApps", "Stake or hold tokens"],
    website: "https://blast.io",
    featured: false,
  },
  {
    id: "10",
    name: "Taiko",
    symbol: "TAIKO",
    description: "Taiko is a decentralized Ethereum-equivalent zkRollup network.",
    status: "active",
    chain: "Ethereum",
    estimatedValue: "$50 - $1,200",
    endDate: "2026-05-09",
    requirements: ["Bridge to Taiko", "Use Taiko dApps", "Join the Taiko community"],
    website: "https://taiko.xyz",
    featured: false,
  },
  {
    id: "11",
    name: "Arbitrum",
    symbol: "ARB",
    description: "Arbitrum is a major Ethereum Layer 2 scaling solution with broad ecosystem support.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$100 - $3,500",
    endDate: "2026-05-09",
    requirements: ["Bridge to Arbitrum", "Use Arbitrum dApps", "Engage with the ecosystem"],
    website: "https://arbitrum.io",
    featured: true,
  },
  {
    id: "12",
    name: "Celestia",
    symbol: "TIA",
    description: "Celestia is a modular blockchain that provides data availability for rollups.",
    status: "active",
    chain: "Modular Chain",
    estimatedValue: "$80 - $2,000",
    endDate: "2026-05-09",
    requirements: ["Use Celestia tools", "Explore modular chains", "Join the community"],
    website: "https://celestia.org",
    featured: false,
  },
  {
    id: "13",
    name: "EigenLayer",
    symbol: "EIGEN",
    description: "EigenLayer is a restaking protocol for Ethereum security and staking services.",
    status: "active",
    chain: "Ethereum",
    estimatedValue: "$60 - $1,800",
    endDate: "2026-05-09",
    requirements: ["Stake ETH on EigenLayer", "Explore restaking", "Follow ecosystem updates"],
    website: "https://eigenlayer.xyz",
    featured: false,
  },
  {
    id: "14",
    name: "Wormhole",
    symbol: "WORM",
    description: "Wormhole is a cross-chain bridge protocol connecting multiple blockchain networks.",
    status: "active",
    chain: "Cross-chain",
    estimatedValue: "$70 - $2,000",
    endDate: "2026-05-09",
    requirements: ["Bridge assets using Wormhole", "Use supported chains", "Stay secure"],
    website: "https://wormhole.com",
    featured: false,
  },
  {
    id: "15",
    name: "Optimism",
    symbol: "OP",
    description: "Optimism is an optimistic rollup built for fast, low-cost Ethereum transactions.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$80 - $2,500",
    endDate: "2026-05-09",
    requirements: ["Bridge to Optimism", "Use Optimism apps", "Stake OP tokens"],
    website: "https://optimism.io",
    featured: false,
  },
  {
    id: "16",
    name: "Polygon zkEVM",
    symbol: "ZKEVM",
    description: "Polygon zkEVM is a zero-knowledge Ethereum scaling solution.",
    status: "active",
    chain: "Polygon",
    estimatedValue: "$90 - $1,800",
    endDate: "2026-05-09",
    requirements: ["Bridge to Polygon zkEVM", "Use zkEVM dApps", "Follow ecosystem news"],
    website: "https://polygon.technology",
    featured: false,
  },
  {
    id: "17",
    name: "Sei Network",
    symbol: "SEI",
    description: "Sei is a high-speed Layer 1 blockchain optimized for trading and DeFi.",
    status: "active",
    chain: "Cosmos",
    estimatedValue: "$50 - $1,500",
    endDate: "2026-05-09",
    requirements: ["Use Sei DEXs", "Stake SEI", "Join the community"],
    website: "https://sei.io",
    featured: false,
  },
  {
    id: "18",
    name: "Sui",
    symbol: "SUI",
    description: "Sui is a Move-based Layer 1 blockchain built for asset-rich applications.",
    status: "active",
    chain: "Sui",
    estimatedValue: "$60 - $1,500",
    endDate: "2026-05-09",
    requirements: ["Use Sui wallet", "Try Sui dApps", "Follow Sui news"],
    website: "https://sui.io",
    featured: false,
  },
  {
    id: "19",
    name: "Aptos",
    symbol: "APT",
    description: "Aptos is a Layer 1 blockchain built for scalability and secure digital ownership.",
    status: "active",
    chain: "Aptos",
    estimatedValue: "$70 - $1,700",
    endDate: "2026-05-09",
    requirements: ["Bridge to Aptos", "Use Aptos apps", "Participate in community events"],
    website: "https://aptoslabs.com",
    featured: false,
  },
  {
    id: "20",
    name: "ZetaChain",
    symbol: "ZETA",
    description: "ZetaChain is an omnichain protocol built for blockchain interoperability.",
    status: "active",
    chain: "Omnichain",
    estimatedValue: "$80 - $1,800",
    endDate: "2026-05-09",
    requirements: ["Use ZetaChain tools", "Bridge assets", "Join the network"],
    website: "https://zetachain.com",
    featured: false,
  },
  {
    id: "21",
    name: "Berachain",
    symbol: "BERA",
    description: "Berachain is an EVM-compatible Layer 1 blockchain with proof-of-liquidity.",
    status: "active",
    chain: "Layer 1",
    estimatedValue: "$50 - $1,400",
    endDate: "2026-05-09",
    requirements: ["Use Berachain apps", "Join the community", "Hold BERA"],
    website: "https://berachain.com",
    featured: false,
  },
  {
    id: "22",
    name: "Node Network",
    symbol: "NODE",
    description: "Node Network is a DeFi-focused Layer 2 with zero-fee scaling and rapid throughput.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$60 - $1,600",
    endDate: "2026-05-09",
    requirements: ["Use Node Network apps", "Bridge assets", "Join the community"],
    website: "https://node.network",
    featured: false,
  },
  {
    id: "23",
    name: "Mantle",
    symbol: "MNT",
    description: "Mantle is a modular Ethereum Layer 2 ecosystem built for scalability.",
    status: "active",
    chain: "Ethereum L2",
    estimatedValue: "$70 - $1,700",
    endDate: "2026-05-09",
    requirements: ["Bridge to Mantle", "Use Mantle dApps", "Follow ecosystem updates"],
    website: "https://mantle.xyz",
    featured: false,
  },
  {
    id: "24",
    name: "KuCoin Web3 Wallet x IOTrader Airdrop",
    symbol: "IOI",
    description: "Take part in the KuCoin Web3 Wallet x IOTrader airdrop for a share of 187,500 IOI across 3,000 winners.",
    status: "active",
    chain: "Multi-chain",
    estimatedValue: "187,500 IOI total (3,000 winners)",
    endDate: "2026-05-31",
    requirements: [
      "Complete the social tasks on X: https://x.com/i/status/2052659867194974329",
      "Join the campaign: https://www.kucoin.com/web3/starter-task?activityId=98",
    ],
    website: "https://www.kucoin.com/web3/starter-task?activityId=98",
    featured: true,
  },
  {
    id: "25",
    name: "Bitget Wallet IOI Token Giveaway",
    symbol: "IOI",
    description: "Join the Bitget Wallet IOI giveaway for eligible regions and complete reward hub tasks to share 187,500 IOI.",
    status: "active",
    chain: "BNB",
    estimatedValue: "187,500 IOI total",
    endDate: "2026-05-21",
    requirements: [
      "Download Bitget Wallet: https://bitgetwallet.onelink.me/6Vx1/xt9vmbjv",
      "Go to Reward Hub, join the event, complete tasks, and earn from the 187,500 IOI prize pool",
      "Join announcement: https://t.me/Bitget_Wallet_Announcement",
    ],
    website: "https://newshare.bwb.global/en/earnCoinsTasks2?uuid=b4a5afe6-c54d-41e6-acac-3e2a55e3c408&_nocache=true&_nobar=true&_needChain=bnb&_chain_tags=bnb",
    featured: true,
  },
]

export const articles: Article[] = [
  {
    id: "1",
    title: "How to Maximize Your Airdrop Earnings in 2026",
    excerpt: "Learn the strategies that successful airdrop hunters use to maximize their token rewards.",
    content: "Full article content here...",
    author: "Alex Chen",
    publishedAt: "2026-04-10",
    readTime: "5 min read",
    category: "Guide",
    slug: "maximize-airdrop-earnings-2026",
  },
  {
    id: "2",
    title: "Understanding zkEVM: The Future of Layer 2 Scaling",
    excerpt: "A deep dive into zero-knowledge technology and how it's revolutionizing blockchain scalability.",
    content: "Full article content here...",
    author: "Sarah Williams",
    publishedAt: "2026-04-08",
    readTime: "8 min read",
    category: "Education",
    slug: "understanding-zkevm-layer2",
  },
  {
    id: "3",
    title: "Top 10 Airdrops to Watch This Month",
    excerpt: "Our curated list of the most promising airdrops happening this month.",
    content: "Full article content here...",
    author: "Mike Johnson",
    publishedAt: "2026-04-05",
    readTime: "4 min read",
    category: "Analysis",
    slug: "top-10-airdrops-april-2026",
  },
  {
    id: "4",
    title: "Airdrop Security: How to Protect Your Wallet",
    excerpt: "Essential security tips to keep your crypto safe while participating in airdrops.",
    content: "Full article content here...",
    author: "Emma Davis",
    publishedAt: "2026-04-02",
    readTime: "6 min read",
    category: "Security",
    slug: "airdrop-security-tips",
  },
  {
    id: "5",
    title: "The Rise of Multi-Chain Airdrops",
    excerpt: "How cross-chain protocols are changing the airdrop landscape.",
    content: "Full article content here...",
    author: "David Park",
    publishedAt: "2026-03-28",
    readTime: "7 min read",
    category: "Trends",
    slug: "multi-chain-airdrops-rise",
  },
  {
    id: "6",
    title: "Getting Started with Layer 2 Solutions",
    excerpt: "A beginner's guide to navigating Ethereum Layer 2 ecosystems.",
    content: "Full article content here...",
    author: "Jessica Moore",
    publishedAt: "2026-03-25",
    readTime: "6 min read",
    category: "Guide",
    slug: "getting-started-layer2",
  },
  {
    id: "7",
    title: "Common Airdrop Scams and How to Avoid Them",
    excerpt: "Protect yourself from fraudulent airdrop schemes and phishing attacks.",
    content: "Full article content here...",
    author: "Robert Chen",
    publishedAt: "2026-03-20",
    readTime: "5 min read",
    category: "Security",
    slug: "avoid-airdrop-scams",
  },
  {
    id: "8",
    title: "The Future of DeFi: What's Coming in 2026",
    excerpt: "Exploring the emerging trends and technologies shaping decentralized finance.",
    content: "Full article content here...",
    author: "Lisa Anderson",
    publishedAt: "2026-03-15",
    readTime: "10 min read",
    category: "Analysis",
    slug: "defi-future-2026",
  },
  {
    id: "9",
    title: "Zero-Knowledge Proofs Explained Simply",
    excerpt: "Understanding zk-proofs and their role in blockchain privacy.",
    content: "Full article content here...",
    author: "Thomas Kumar",
    publishedAt: "2026-03-10",
    readTime: "9 min read",
    category: "Education",
    slug: "zero-knowledge-proofs",
  },
  {
    id: "10",
    title: "Staking Rewards: Maximize Your Passive Income",
    excerpt: "Learn strategies to earn the best returns from staking your crypto.",
    content: "Full article content here...",
    author: "Michelle Zhang",
    publishedAt: "2026-03-05",
    readTime: "7 min read",
    category: "Guide",
    slug: "staking-rewards-guide",
  },
  {
    id: "11",
    title: "NFT Airdrops: Opportunities and Risks",
    excerpt: "A comprehensive look at NFT airdrop strategies and potential pitfalls.",
    content: "Full article content here...",
    author: "Brandon Lee",
    publishedAt: "2026-02-28",
    readTime: "8 min read",
    category: "Analysis",
    slug: "nft-airdrops-guide",
  },
  {
    id: "12",
    title: "Web3 Wallets: Security Best Practices",
    excerpt: "Essential tips for keeping your cryptocurrency wallets secure.",
    content: "Full article content here...",
    author: "Sarah Johnson",
    publishedAt: "2026-02-20",
    readTime: "6 min read",
    category: "Security",
    slug: "web3-wallet-security",
  },
]

export function getStatusColor(status: AirdropStatus): string {
  switch (status) {
    case "active":
      return "bg-emerald-500/20 text-emerald-400 border-emerald-500/30"
    case "upcoming":
      return "bg-primary/20 text-primary border-primary/30"
    case "ended":
      return "bg-muted text-muted-foreground border-border"
    default:
      return "bg-muted text-muted-foreground border-border"
  }
}
